### PR TITLE
BlockQueue: accept block announcements from any connected peer

### PR DESCRIPTION
**Pull request by styppo**

### CODE REVIEW

**Review by ii-cruz — APPROVED** [review]
LGTM

**Review by nibhar — CHANGES_REQUESTED** [review]
As this supersedes #2889 I think as stated in that PR the `macro_head_hash` should remain in the response.

**Comment by styppo** [comment]
Added macro and election head hash to the response in c064cc1.

**Review by nibhar — APPROVED** [review]
Please create an Issue to track utilizing the macro_heads.

**Pull request merged**
