### PR TITLE
Make rewards explicit transactions

### PR DESCRIPTION
**Pull request by brunoffranca**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.

## What's in this pull request?

Creates transactions that match the reward inherents. The main objective is to make the rewards easier to fetch and handle for block explorers and such.

### CODE REVIEW

**Comment by sisou** [comment]
@brunoffranca If I'm seeing this right rewards are now stored in the history store twice: once as an inherent and once as a transaction. Is that on purpose?

**Comment by sisou** [comment]
Oh, actually not. The reward _transactions_ are not stored in the history store, only the reward inherents. Still, is that on purpose?

**Comment by brunoffranca** [comment]
Actually, they should be both stored in the History Store. So, it is very much not on purpose. Where did you see that they were not stored?

**Comment by sisou** [comment]
Here the transactions are not included in the extended txs that get added to the history store, instead an empty array is passed in:
https://github.com/nimiq/core-rs-albatross/blob/c04516edbc93da6fc7454633149e91a3998d9c1d/block-production-albatross/src/lib.rs#L226

**Comment by brunoffranca** [comment]
Good catch. I guess Nata forgot to put the transactions from line 217 in there (and I didn't see that during review). Easy fix though, I'll do it tonight.

**Comment by brunoffranca** [comment]
I ended taking 8 days off, so this got somewhat delayed. Furthermore, we couldn't have both the transactions and the inherents into the history tree since full nodes use the history tree when syncing. The solution is a bit more involved, it is in PR #260 . Anyway, the history tree now only contains the reward _transactions_, you can get them by simply asking for a macro block transactions.
P.S. The history tree now only stores slash inherents. The reward, finalize batch, and finalize epoch inherents no longer appear in the history tree.

**Comment by sisou** [comment]
@brunoffranca Just tested this out for the first time. The reward transactions have a `validityStartHeight` of macro-block-height - 1. So for macroblock # 128 the validity start height is 127. I think it makes more sense to have the macro block height as the VSH. Do you think so, too, or is this not relevant?

**Comment by brunoffranca** [comment]
What do you mean, the VSH?

**Comment by sisou** [comment]
ValidityStartHeight. Too lazy to type it out.

**Comment by brunoffranca** [comment]
You can always copy-paste. xD
It's nitpicking, but sure, here you go. c222764

**Pull request merged**
