### PR TITLE
Network updates

### PR DESCRIPTION
**Pull request by vlvrd**

### CODE REVIEW

**Comment by sisou** [comment]
Running this outside the context of our docker-setup (directly on my Linux with `cargo run --bin nimiq-client`, trying to connect to the correctly running docker validators), I get the following panic:

```
ERROR panic                | thread 'libp2p-swarm-task-1' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime': /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/name_server/connection_provider.rs:345
   0: log_panics::init::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/core/src/panicking.rs:92:14
   6: core::option::expect_failed
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/core/src/option.rs:1241:5
   7: core::option::Option<T>::expect
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   8: tokio::task::spawn::spawn
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/task/spawn.rs:132:28
   9: <trust_dns_resolver::name_server::connection_provider::tokio_runtime::TokioHandle as trust_dns_resolver::name_server::connection_provider::Spawn>::spawn_bg
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/name_server/connection_provider.rs:345:25
  10: <trust_dns_resolver::name_server::connection_provider::ConnectionFuture<R> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/name_server/connection_provider.rs:277:17
  11: trust_dns_resolver::name_server::name_server::NameServer<C,P>::connected_mut_client::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/name_server/name_server.rs:114:30
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: trust_dns_resolver::name_server::name_server::NameServer<C,P>::inner_send::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/name_server/name_server.rs:134:26
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  16: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/map.rs:55:37
  17: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  18: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/stream/futures_unordered/mod.rs:542:17
  19: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/stream/stream/mod.rs:1415:9
  20: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/stream/stream/next.rs:35:9
  21: trust_dns_resolver::name_server::name_server_pool::parallel_conn_loop::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/name_server/name_server_pool.rs:332:34
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  23: trust_dns_resolver::name_server::name_server_pool::NameServerPool<C,P>::try_send::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/name_server/name_server_pool.rs:196:9
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  25: <trust_dns_resolver::name_server::name_server_pool::NameServerPool<C,P> as trust_dns_proto::xfer::dns_handle::DnsHandle>::send::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/name_server/name_server_pool.rs:238:27
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  28: futures_util::future::future::FutureExt::poll_unpin
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/mod.rs:562:9
  29: <trust_dns_proto::xfer::retry_dns_handle::RetrySendFuture<H> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.2/src/xfer/retry_dns_handle.rs:94:19
  30: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  31: trust_dns_resolver::caching_client::CachingClient<C,E>::inner_lookup::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/caching_client.rs:178:32
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  33: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  34: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  35: futures_util::future::future::FutureExt::poll_unpin
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/mod.rs:562:9
  36: <trust_dns_resolver::lookup::LookupFuture<C,E> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/lookup.rs:273:25
  37: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/either.rs:73:33
  38: trust_dns_resolver::async_resolver::AsyncResolver<C,P>::inner_lookup::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/async_resolver.rs:338:9
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  40: trust_dns_resolver::async_resolver::AsyncResolver<C,P>::ipv4_lookup::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.20.2/src/async_resolver.rs:92:13
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  42: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/map.rs:55:37
  43: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  44: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  45: <libp2p_dns::GenDnsConfig<T,C,P> as libp2p_core::transport::Transport>::dial::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-dns-0.28.1/src/lib.rs:226:27
  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  47: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  48: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/either.rs:73:33
  49: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  50: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/try_future/into_future.rs:35:9
  51: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/map.rs:55:37
  52: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  53: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  54: libp2p_websocket::framed::WsConfig<T>::dial_once::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-websocket-0.29.0/src/framed.rs:284:22
  55: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  56: <libp2p_websocket::framed::WsConfig<T> as libp2p_core::transport::Transport>::dial::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-websocket-0.29.0/src/framed.rs:246:23
  57: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  58: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  59: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  60: <libp2p_core::transport::map::MapFuture<T,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.28.3/src/transport/map.rs:133:26
  61: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  62: <libp2p_core::either::EitherFuture<AFuture,BFuture> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.28.3/src/either.rs:390:43
  63: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  64: <libp2p_core::transport::and_then::AndThenFuture<TFut,TMap,TMapOut> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.28.3/src/transport/and_then.rs:157:38
  65: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  66: <libp2p_core::transport::and_then::AndThenFuture<TFut,TMap,TMapOut> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.28.3/src/transport/and_then.rs:157:38
  67: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  68: <libp2p_core::transport::timeout::Timeout<InnerFut> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.28.3/src/transport/timeout.rs:175:15
  69: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  70: <libp2p_core::transport::map::MapFuture<T,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.28.3/src/transport/map.rs:133:26
  71: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  72: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/try_future/into_future.rs:35:9
  73: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/map.rs:55:37
  74: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  75: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  76: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  77: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  78: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/try_future/into_future.rs:35:9
  79: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/map.rs:55:37
  80: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  81: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  82: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  83: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/try_future/into_future.rs:35:9
  84: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/map.rs:55:37
  85: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  86: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  87: <F as futures_core::future::TryFuture>::try_poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.14/src/future.rs:84:9
  88: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/try_future/try_flatten.rs:48:34
  89: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  90: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/lib.rs:102:13
  91: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  92: futures_util::future::future::FutureExt::poll_unpin
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/mod.rs:562:9
  93: <libp2p_core::connection::manager::task::Task<F,M,H,I,O,E> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.28.3/src/connection/manager/task.rs:221:27
  94: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:120:9
  95: <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.14/src/future_obj.rs:86:13
  96: <futures_task::future_obj::FutureObj<T> as core::future::future::Future>::poll
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.14/src/future_obj.rs:133:9
  97: futures_util::future::future::FutureExt::poll_unpin
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/future/mod.rs:562:9
  98: futures_executor::thread_pool::Task::run
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.14/src/thread_pool.rs:326:27
  99: futures_executor::thread_pool::PoolState::work
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.14/src/thread_pool.rs:160:39
 100: futures_executor::thread_pool::ThreadPoolBuilder::create::{{closure}}
             at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.14/src/thread_pool.rs:288:42
 101: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
 102: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:481:17
 103: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
 104: std::panicking::try::do_call
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
 105: __rust_try
 106: std::panicking::try
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
 107: std::panic::catch_unwind
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
 108: std::thread::Builder::spawn_unchecked::{{closure}}
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:480:30
 109: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
 110: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9684258936dabda2ba49d4c67f041a6baf388348/library/std/src/sys/unix/thread.rs:71:17
 111: start_thread
 112: __clone
```

**Comment by Eligioo** [comment]
@sisou maybe different versions of Tokio are being used across crates. Then one crate tries to spawn a task and a different Tokio runtime is actually being used.

**Comment by vlvrd** [comment]
@sisou @Eligioo it's exactly that, it's an issue with Tokio and libp2p 0.36. We're downgrading libp2p to a previous version outside this PR to fix this error.

**Comment by sisou** [comment]
Rebased onto `albatross` manually up to commit https://github.com/nimiq/core-rs-albatross/commit/36e9428a256395b593ac8272173dff319a734322.

**Pull request closed without merging**
