### PR TITLE
chore: fix some comments

### PR DESCRIPTION
**Pull request by zhedazijingang**
## What's in this pull request?

 fix some comments

...
## Pull request checklist

- [ ] All tests pass. The project builds and runs.
- [ ] I have resolved any merge conflicts.
- [ ] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

**Review by Eligioo — APPROVED** [review]
LGTM, thank you for fixing those

**Comment by Eligioo** [comment]
@zhedazijingang can you make sure the commit is signed?

**Comment by zhedazijingang** [comment]
> @zhedazijingang can you make sure the commit is signed?

Of course. Signed

**Comment by hrxi** [comment]
Rebased for merging.

**Comment by hrxi** [comment]
Thanks!

**Pull request merged**
