### PR TITLE
LiveSync: always poll BlockQueue, even with a push future in progress

### LINKED ISSUE #2494: Peers vanish from live sync

### PR DESCRIPTION
**Pull request by styppo**
Closes #2494

### CODE REVIEW

**Review by hrxi — APPROVED** [review]
LGTM, thanks!

**Comment by hrxi** [comment]
Rebasing to merge.

**Comment by hrxi** [comment]
Actually, there are test failures. I can reproduce them locally.

**Comment by viquezclaudio** [comment]
This fix seems to be causing/related to  #2576

**Comment by styppo** [comment]
Superseded by #2607

**Pull request closed without merging**
