### PR TITLE
Port to Tokio 0.2

### PR DESCRIPTION
**Pull request by riptl**
Mega PR to port all asynchronous code to async/.await and tokio-0.2.

List of changes:
 - [x] @jgraef: Port validator to Tokio 2
 - [x] @jgraef: Port metrics server to Tokio 2
 - [x] @jgraef / @terorie: Use `tokio::main` in client
 - [ ] @jgraef / @terorie: Revise lib interface
   - [ ] Call style: async-blocking `async fn run()` or non-blocking `fn start()`?
   - [ ] Shutdown mechanism (blocks #29)
 - [x] @terorie: Port network to Tokio 2
   - [x] `WebSocketConnector`: Remove `tk-listen`, replace with custom accept loop
   - [ ] @styppo: Discuss behavior if CONNECTIONS_MAX reached
   - [x] Run all connection handlers in spawned future with external shutdown signal
   - [x] Use `std::task::Poll` instead of `Async`, new Stream/Sink/Future traits
   - [x] Refactor message stream: Make transport-independent, adapt to new `start_send`/`poll_ready` sink
   - [x] Fix message chunk pipelining
   - [x] Unit tests for message stream
 - [x] @terorie: Port consensus to Tokio 2
   - `AccountsChunkCache`: use `std::task::Waker` instead of `futures-0.1::task::Task`
 - [x] @terorie: Port handel to Tokio 2
 - ~~@jgraef: Separate crate for handel primitives (no dep on Tokio)~~
 - [x] @terorie: Port rpc-server to Tokio 2
 - [x] @terorie: Port ws-rpc-server to Tokio 2

### CODE REVIEW

**Comment by riptl** [comment]
The new message chunker is bugged.
```
 2020-01-25 01:10:50.952 ERROR stream               | Max message size exceeded (1421545052 > 10485760)
 2020-01-25 01:10:50.952 DEBUG channel              | Stream with peer closed with error: Received a message with a size exceeding the defined maximum (AddressInfo {peer_address: ws://7.0.1.152:8443/ca29825adf54ca7e0c721883c9bff7d0, net_address: 7.0.1.152, })
```

**Comment by terorie** [comment]
[Tokio 0.2 support](https://trello.com/c/2g4lMpge/57-tokio-02-support)

**Comment by terorie** [comment]
[Tokio 0.2 support](https://trello.com/c/2g4lMpge/57-tokio-02-support)

**Comment by riptl** [comment]
Closing stale PR.

**Comment by jgraef** [comment]
Afaik, this should stay open. At some point we should switch to Tokio 0.2.

**Comment by riptl** [comment]
@paberr Should I rebase this?

**Pull request closed without merging**
